"""add_extended_profile_fields

Revision ID: 7679cb248be6
Revises: 042309d39382
Create Date: 2026-07-04 11:09:41.310070+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7679cb248be6'
down_revision: Union[str, None] = '042309d39382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_snapshots', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('profile_snapshots', sa.Column('biography_with_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profile_snapshots', sa.Column('bio_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profile_snapshots', sa.Column('pronouns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profile_snapshots', sa.Column('external_url', sa.String(length=2048), nullable=True))
    op.add_column('profile_snapshots', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('is_business_account', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('is_professional_account', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('category_name', sa.String(length=255), nullable=True))
    op.add_column('profile_snapshots', sa.Column('category_enum', sa.String(length=255), nullable=True))
    op.add_column('profile_snapshots', sa.Column('overall_category_name', sa.String(length=255), nullable=True))
    op.add_column('profile_snapshots', sa.Column('business_contact_method', sa.String(length=255), nullable=True))
    op.add_column('profile_snapshots', sa.Column('business_email', sa.String(length=255), nullable=True))
    op.add_column('profile_snapshots', sa.Column('business_phone_number', sa.String(length=255), nullable=True))
    op.add_column('profile_snapshots', sa.Column('highlight_reel_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('profile_snapshots', sa.Column('has_clips', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('has_guides', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('has_channel', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('mutual_followers_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_snapshots', 'mutual_followers_count')
    op.drop_column('profile_snapshots', 'has_channel')
    op.drop_column('profile_snapshots', 'has_guides')
    op.drop_column('profile_snapshots', 'has_clips')
    op.drop_column('profile_snapshots', 'highlight_reel_count')
    op.drop_column('profile_snapshots', 'business_phone_number')
    op.drop_column('profile_snapshots', 'business_email')
    op.drop_column('profile_snapshots', 'business_contact_method')
    op.drop_column('profile_snapshots', 'overall_category_name')
    op.drop_column('profile_snapshots', 'category_enum')
    op.drop_column('profile_snapshots', 'category_name')
    op.drop_column('profile_snapshots', 'is_professional_account')
    op.drop_column('profile_snapshots', 'is_business_account')
    op.drop_column('profile_snapshots', 'is_verified')
    op.drop_column('profile_snapshots', 'external_url')
    op.drop_column('profile_snapshots', 'pronouns')
    op.drop_column('profile_snapshots', 'bio_links')
    op.drop_column('profile_snapshots', 'biography_with_entities')
    op.drop_column('profile_snapshots', 'biography')
    # ### end Alembic commands ###
