"""add_extended_post_comment_profile_fields

Revision ID: a69595866b73
Revises: ab1928095cda
Create Date: 2026-07-04 13:26:02.643408+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a69595866b73'
down_revision: Union[str, None] = 'ab1928095cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_profile_pic_url', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('author_is_private', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('comments', sa.Column('liked_by_creator', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('comments', sa.Column('reported_as_spam', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('posts', sa.Column('accessibility_caption', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('is_paid_partnership', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('posts', sa.Column('product_type', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('music_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('original_height', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('original_width', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('coauthor_producers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('tagged_usernames', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('counts_disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('is_meta_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('hides_like_view_counts', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('has_ar_effects', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('profile_snapshots', sa.Column('business_category_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_snapshots', 'business_category_name')
    op.drop_column('profile_snapshots', 'has_ar_effects')
    op.drop_column('profile_snapshots', 'hides_like_view_counts')
    op.drop_column('profile_snapshots', 'is_meta_verified')
    op.drop_column('posts', 'counts_disabled')
    op.drop_column('posts', 'tagged_usernames')
    op.drop_column('posts', 'coauthor_producers')
    op.drop_column('posts', 'locations')
    op.drop_column('posts', 'original_width')
    op.drop_column('posts', 'original_height')
    op.drop_column('posts', 'music_metadata')
    op.drop_column('posts', 'product_type')
    op.drop_column('posts', 'is_paid_partnership')
    op.drop_column('posts', 'accessibility_caption')
    op.drop_column('comments', 'reported_as_spam')
    op.drop_column('comments', 'is_edited')
    op.drop_column('comments', 'liked_by_creator')
    op.drop_column('comments', 'author_is_private')
    op.drop_column('comments', 'author_profile_pic_url')
    # ### end Alembic commands ###
