"""add_engagement_timing_signals

Revision ID: ab1928095cda
Revises: e2c194915afc
Create Date: 2026-07-04 12:56:06.022153+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1928095cda'
down_revision: Union[str, None] = 'e2c194915afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_from_creator', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_comments_is_from_creator'), 'comments', ['is_from_creator'], unique=False)
    op.add_column('feature_store', sa.Column('first_comment_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feature_store', sa.Column('time_to_first_comment_s', sa.Integer(), nullable=True))
    op.add_column('feature_store', sa.Column('creator_reply_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('feature_store', sa.Column('time_to_first_creator_reply_s', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_store', 'time_to_first_creator_reply_s')
    op.drop_column('feature_store', 'creator_reply_count')
    op.drop_column('feature_store', 'time_to_first_comment_s')
    op.drop_column('feature_store', 'first_comment_at')
    op.drop_index(op.f('ix_comments_is_from_creator'), table_name='comments')
    op.drop_column('comments', 'is_from_creator')
    # ### end Alembic commands ###
